sh decompile.sh /Users/sanbo/Desktop/priv-app/Provision/Provision.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Music/Music.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/YellowPage/YellowPage.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/AuthManager/AuthManager.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/PersonalAssistant/PersonalAssistant.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/UserDictionaryProvider/UserDictionaryProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/PermissionController/PermissionController.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ONS/ONS.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/SoundRecorder/SoundRecorder.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiExtraPhoto/MiuiExtraPhoto.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Calendar/Calendar.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/CloudBackup/CloudBackup.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/InputDevices/InputDevices.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/FusedLocation/FusedLocation.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MediaProvider/MediaProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/LocalTransport/LocalTransport.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiSettings/MiSettings.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/SecurityCenter/SecurityCenter.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiFreeformService/MiuiFreeformService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/CloudServiceSysbase/CloudServiceSysbase.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiHome/MiuiHome.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ManagedProvisioning/ManagedProvisioning.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Shell/Shell.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/DownloadProviderUi/DownloadProviderUi.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/RtMiCloudSDK/RtMiCloudSDK.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiRcs/MiRcs.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/GoogleExtServicesPrebuilt/GoogleExtServicesPrebuilt.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiSystemUI/MiuiSystemUI.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/TelephonyProvider/TelephonyProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Contacts/Contacts.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ContentExtension/ContentExtension.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/DMRegService/DMRegService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/FindDevice/FindDevice.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ProxyHandler/ProxyHandler.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/SharedStorageBackup/SharedStorageBackup.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/CallLogBackup/CallLogBackup.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiService/MiService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MusicFX/MusicFX.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Mms/Mms.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/WfdService/WfdService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/com.qualcomm.location/com.qualcomm.location.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Browser/Browser.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Telecom/Telecom.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/PackageInstaller/PackageInstaller.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiGallery/MiuiGallery.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiPackageInstaller/MiuiPackageInstaller.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/CalendarProvider/CalendarProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/SettingsProvider/SettingsProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MmsService/MmsService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/QuickSearchBox/QuickSearchBox.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiVideo/MiuiVideo.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiGameCenterSDKService/MiGameCenterSDKService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/BlockedNumberProvider/BlockedNumberProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/StatementService/StatementService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiuiCamera/MiuiCamera.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/GoogleDocumentsUIPrebuilt/GoogleDocumentsUIPrebuilt.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MiShare/MiShare.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/BackupRestoreConfirmation/BackupRestoreConfirmation.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Backup/Backup.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/CtsShimPrivPrebuilt/CtsShimPrivPrebuilt.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/DynamicSystemInstallationService/DynamicSystemInstallationService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/ContactsProvider/ContactsProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/TeleService/TeleService.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/NewHome/NewHome.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/VpnDialogs/VpnDialogs.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/Tag/Tag.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/InCallUI/InCallUI.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/MtpDocumentsProvider/MtpDocumentsProvider.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/PlatformNetworkPermissionConfig/PlatformNetworkPermissionConfig.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/InProcessNetworkStack/InProcessNetworkStack.apk
sh decompile.sh /Users/sanbo/Desktop/priv-app/DownloadProvider/DownloadProvider.apk
